version: "3.8"

services:
  # ===========================
  # SPRING BOOT BACKEND
  # ===========================
  vpdf-backend:
    build:
      context: ./vpdf-backend
      dockerfile: Dockerfile
    container_name: vpdf-backend
    ports:
      - "8080:8080"
    environment:
      # Cluster Cassandra NATIF (LAN) : seeds / contact points
      SPRING_CASSANDRA_CONTACT_POINTS: 192.168.150.123,192.168.150.107,192.168.150.102
      SPRING_CASSANDRA_PORT: 9042
      SPRING_CASSANDRA_KEYSPACE_NAME: vpdf
      SPRING_CASSANDRA_LOCAL_DATACENTER: datacenter1
    networks: [vpdf-net]
    restart: on-failure

  # ===========================
  # NEXT.JS FRONTEND
  # ===========================
  vpdf-frontend:
    build:
      context: ./vpdf-frontend
      dockerfile: Dockerfile
    container_name: vpdf-frontend
    ports:
      - "3000:3000"
    environment:
      # Dans Docker, "localhost" = le conteneur lui-même. On vise le service backend via son nom Docker.
      NEXT_PUBLIC_API_URL: http://vpdf-backend:8080
    networks: [vpdf-net]
    depends_on: [vpdf-backend]

volumes:
  {}

networks:
  vpdf-net:
    driver: bridge