server:
  port: 8080

spring:
  cassandra:
    contact-points: ${SPRING_CASSANDRA_CONTACT_POINTS:192.168.150.123,192.168.150.107,192.168.150.102}
    port: ${SPRING_CASSANDRA_PORT:9042}
    keyspace-name: ${SPRING_CASSANDRA_KEYSPACE_NAME:ventespleindefoin}
    local-datacenter: ${SPRING_CASSANDRA_LOCAL_DATACENTER:dc1}
    schema-action: none
    request:
      consistency: ${SPRING_CASSANDRA_CONSISTENCY:LOCAL_QUORUM}

logging:
  level:
    com.vpdf: DEBUG
    com.datastax: WARN
    org.springframework.data.cassandra: INFO

---
spring:
  config:
    activate:
      on-profile: docker
  cassandra:
    contact-points: ${SPRING_CASSANDRA_CONTACT_POINTS:192.168.150.123,192.168.150.107,192.168.150.102}
    port: ${SPRING_CASSANDRA_PORT:9042}
    keyspace-name: ${SPRING_CASSANDRA_KEYSPACE_NAME:ventespleindefoin}
    local-datacenter: ${SPRING_CASSANDRA_LOCAL_DATACENTER:dc1}
    schema-action: none
    request:
      consistency: ${SPRING_CASSANDRA_CONSISTENCY:ONE}
